version: '3'
services:
  radius:
    build: .
    env_file:
      - .env
    ports:
      - "1812:1812/udp"
    environment:
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - RADIUS_SECRET=${RADIUS_SECRET}
      - PORT=${PORT}
      - DEBUG=*
